# Generated by Django 4.1 on 2022-10-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_auto_20221011_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_old',
        ),
    ]
