# Generated by Django 4.1.2 on 2022-10-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_auto_20221013_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_old',
        ),
    ]
